import { MenuItem, Review, Offer, GalleryImage, CMSContent, BusinessHours } from './types'

export const menuItems: MenuItem[] = [
  {
    id: '1',
    name: 'Pastata Ram',
    nameAr: 'باستاتا رام',
    description: 'Pasta with chicken, roasted tomatoes, eggplant & special herbs',
    descriptionAr: 'باستا مع الدجاج والطماطم المشوية والباذنجان والأعشاب الخاصة',
    price: 27,
    category: 'pasta',
    image: 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=600&q=80',
    tags: ['bestseller', 'featured', 'recommended'],
    available: true,
    featured: true,
    bestseller: true,
    calories: 520,
  },
  {
    id: '2',
    name: 'Ramcine',
    nameAr: 'رامسين',
    description: 'Fettuccine with chicken, cream sauce & mushrooms',
    descriptionAr: 'فيتوتشيني مع الدجاج والكريمة والمشروم',
    price: 27,
    category: 'pasta',
    image: 'https://images.unsplash.com/photo-1555949258-eb67b1ef0ceb?w=600&q=80',
    tags: ['featured', 'recommended'],
    available: true,
    featured: true,
    bestseller: false,
    calories: 580,
  },
  {
    id: '3',
    name: 'Pastata Balls',
    nameAr: 'باستاتا بولز',
    description: 'Crispy potato balls stuffed with mozzarella',
    descriptionAr: 'كرات بطاطس مقرمشة محشوة بالموزاريلا',
    price: 14,
    category: 'sides',
    image: 'https://images.unsplash.com/photo-1574484284002-952d92456975?w=600&q=80',
    tags: ['featured', 'snack'],
    available: true,
    featured: true,
    bestseller: true,
    calories: 280,
  },
  {
    id: '4',
    name: 'Soft Drink',
    nameAr: 'مشروب غازي',
    description: 'Refreshing soft drink',
    descriptionAr: 'مشروب غازي منعش',
    price: 2,
    category: 'drinks',
    image: 'https://images.unsplash.com/photo-1544145945-f90425340c7e?w=600&q=80',
    tags: [],
    available: true,
    featured: false,
    bestseller: false,
    calories: 140,
  },
  {
    id: '5',
    name: 'Water',
    nameAr: 'مياه',
    description: 'Fresh mineral water',
    descriptionAr: 'مياه معدنية طازجة',
    price: 1,
    category: 'drinks',
    image: 'https://images.unsplash.com/photo-1548839140-29a749e1cf4d?w=600&q=80',
    tags: [],
    available: true,
    featured: false,
    bestseller: false,
    calories: 0,
  },
]

export const reviews: Review[] = [
  {
    id: '1',
    customerName: 'محمد العمري',
    rating: 5,
    comment: 'تجربة رائعة! الباستا لذيذة جداً والخدمة سريعة. أفضل مطعم باستا في جدة بدون شك.',
    date: new Date('2024-12-10'),
    verified: true,
    featured: true,
    approved: true,
  },
  {
    id: '2',
    customerName: 'Sarah Al-Rashid',
    rating: 5,
    comment: 'Amazing pasta! The Pastata Ram is absolutely divine. Love the premium feel of the place.',
    date: new Date('2024-12-08'),
    verified: true,
    featured: true,
    approved: true,
  },
  {
    id: '3',
    customerName: 'نورة الزهراني',
    rating: 5,
    comment: 'الباستا بولز رهيبة! القرمشة مثالية والجبن يذوب في الفم. سأعود بالتأكيد.',
    date: new Date('2024-12-05'),
    verified: true,
    featured: true,
    approved: true,
  },
  {
    id: '4',
    customerName: 'Ahmed Hassan',
    rating: 4,
    comment: 'Great taste and presentation. The Ramcine pasta is creamy and rich. Highly recommend!',
    date: new Date('2024-12-01'),
    verified: true,
    featured: false,
    approved: true,
  },
  {
    id: '5',
    customerName: 'فيصل القحطاني',
    rating: 5,
    comment: 'مكان ممتاز وطعام استثنائي. التصميم عصري جداً والجودة تستحق كل ريال.',
    date: new Date('2024-11-28'),
    verified: true,
    featured: true,
    approved: true,
  },
  {
    id: '6',
    customerName: 'Lina Khalid',
    rating: 5,
    comment: 'Absolutely loved the experience! The pasta is fresh, the flavors are incredible, and the ambiance is so Instagram-worthy!',
    date: new Date('2024-11-25'),
    verified: true,
    featured: false,
    approved: true,
  },
]

export const offers: Offer[] = [
  {
    id: '1',
    title: 'Duo Combo',
    titleAr: 'عرض الثنائي',
    description: '2 Pasta dishes + 2 drinks at a special price',
    descriptionAr: '٢ وجبة باستا + ٢ مشروب بسعر مميز',
    discount: 15,
    discountType: 'percentage',
    code: 'DUO15',
    image: 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=600&q=80',
    validUntil: new Date('2025-02-28'),
    active: true,
    featured: true,
  },
  {
    id: '2',
    title: 'Family Feast',
    titleAr: 'وجبة العائلة',
    description: '4 Pasta dishes + 4 drinks + Pastata Balls',
    descriptionAr: '٤ وجبات باستا + ٤ مشروبات + باستاتا بولز',
    discount: 20,
    discountType: 'percentage',
    code: 'FAMILY20',
    image: 'https://images.unsplash.com/photo-1555949258-eb67b1ef0ceb?w=600&q=80',
    validUntil: new Date('2025-01-31'),
    active: true,
    featured: true,
  },
  {
    id: '3',
    title: 'Happy Hour',
    titleAr: 'ساعة السعادة',
    description: 'Get 10 SAR off any order between 3-5 PM',
    descriptionAr: 'احصل على خصم ١٠ ريال على أي طلب من ٣-٥ عصراً',
    discount: 10,
    discountType: 'fixed',
    code: 'HAPPY10',
    image: 'https://images.unsplash.com/photo-1574484284002-952d92456975?w=600&q=80',
    validUntil: new Date('2025-03-31'),
    active: true,
    featured: false,
  },
]

export const galleryImages: GalleryImage[] = [
  { id: '1', url: 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=800&q=80', alt: 'Pastata Ram', altAr: 'باستاتا رام', category: 'food', featured: true },
  { id: '2', url: 'https://images.unsplash.com/photo-1555949258-eb67b1ef0ceb?w=800&q=80', alt: 'Ramcine Pasta', altAr: 'رامسين باستا', category: 'food', featured: true },
  { id: '3', url: 'https://images.unsplash.com/photo-1574484284002-952d92456975?w=800&q=80', alt: 'Pastata Balls', altAr: 'باستاتا بولز', category: 'food', featured: true },
  { id: '4', url: 'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=800&q=80', alt: 'Premium Pasta', altAr: 'باستا مميزة', category: 'food', featured: false },
  { id: '5', url: 'https://images.unsplash.com/photo-1473093226795-af9932fe5856?w=800&q=80', alt: 'Fresh Ingredients', altAr: 'مكونات طازجة', category: 'ingredients', featured: true },
  { id: '6', url: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&q=80', alt: 'Food Experience', altAr: 'تجربة غذائية', category: 'experience', featured: false },
  { id: '7', url: 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=800&q=80', alt: 'Fresh Food', altAr: 'طعام طازج', category: 'food', featured: true },
  { id: '8', url: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=800&q=80', alt: 'Pizza & Pasta', altAr: 'بيتزا وباستا', category: 'food', featured: false },
  { id: '9', url: 'https://images.unsplash.com/photo-1498654896293-37aacf113fd9?w=800&q=80', alt: 'Gourmet Dish', altAr: 'طبق فاخر', category: 'food', featured: true },
]

export const businessHours: BusinessHours[] = [
  { day: 'Sunday', dayAr: 'الأحد', open: '12:00', close: '12:00', closed: false },
  { day: 'Monday', dayAr: 'الاثنين', open: '12:00', close: '12:00', closed: false },
  { day: 'Tuesday', dayAr: 'الثلاثاء', open: '12:00', close: '12:00', closed: false },
  { day: 'Wednesday', dayAr: 'الأربعاء', open: '12:00', close: '12:00', closed: false },
  { day: 'Thursday', dayAr: 'الخميس', open: '12:00', close: '01:00', closed: false },
  { day: 'Friday', dayAr: 'الجمعة', open: '13:00', close: '01:00', closed: false },
  { day: 'Saturday', dayAr: 'السبت', open: '12:00', close: '01:00', closed: false },
]

export const cmsContent: CMSContent = {
  heroTitle: 'A Modern Pasta Experience Combining Elegance & Exceptional Taste',
  heroTitleAr: 'تجربة باستا عصرية تجمع بين الأناقة والطعم الاستثنائي',
  heroSubtitle: 'Italian flavors carefully crafted to give you an unforgettable experience',
  heroSubtitleAr: 'نكهات إيطالية مصممة بعناية لتمنحكم تجربة لا تُنسى',
  heroImage: 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=1600&q=90',
  aboutText: 'PASTATARAM is a premium fast-casual pasta brand born in Jeddah. We believe great pasta should be accessible, fast, and absolutely delicious. Every dish is crafted with premium Italian-inspired ingredients.',
  aboutTextAr: 'باستاتا رام هي علامة تجارية للباستا الفاخرة غير الرسمية ولدت في جدة. نؤمن بأن الباستا الرائعة يجب أن تكون في متناول الجميع، سريعة، ولذيذة تماماً. كل طبق يُصنع بمكونات فاخرة مستوحاة من الطراز الإيطالي.',
  businessHours,
  socialLinks: {
    instagram: 'https://instagram.com/pastataram',
    tiktok: 'https://tiktok.com/@pastataram',
    snapchat: 'https://snapchat.com/add/pastataram',
    whatsapp: 'https://wa.me/966501938696',
  },
  whatsappNumber: '966501938696',
  phone: '050 193 8696',
  address: 'Jeddah – Al Qurainiyah – Street 80 – Next to Al-Salah Al-Eqtisadiyah Hall',
  addressAr: 'جدة - القرنية - شارع 80 - بجوار الصالة الاقتصادية',
}
