import { MenuItem, Review, Offer, GalleryImage, CMSContent, BusinessHours } from './types'

export const menuItems: MenuItem[] = [
  {
    id: '1',
    name: 'Pastata Ram',
    nameAr: 'باستاتا رام',
    description: 'Signature pasta with tender chicken, grilled tomatoes & roasted eggplant, tossed in premium Chinese herbs and a rich, distinctive sauce.',
    descriptionAr: 'باستا مميزة مع قطع الدجاج الطازجة والطماطم المشوية والباذنجان المشوي، ممزوجة بالأعشاب الصينية الفاخرة وصوص غني يمنحها نكهة استثنائية.',
    price: 27,
    category: 'pasta',
    image: '/images/f1.png',
    tags: ['bestseller', 'featured', 'recommended'],
    available: true,
    featured: true,
    bestseller: true,
    calories: 520,
  },
  {
    id: '2',
    name: 'Ramcine',
    nameAr: 'رام شيني',
    description: 'Creamy fettuccine with tender chicken and fresh mushrooms, finished with rich cream and premium Chinese herbs.',
    descriptionAr: 'فيتوتشيني كريمية مع الدجاج الطري والمشروم الطازج، محضرة بالكريمة الغنية والأعشاب الصينية الفاخرة لتجربة مذاق فريدة.',
    price: 27,
    category: 'pasta',
    image: '/images/f2.png',
    tags: ['featured', 'recommended'],
    available: true,
    featured: true,
    bestseller: false,
    calories: 580,
  },
  {
    id: '3',
    name: 'Pastata Balls',
    nameAr: 'باستاتا بولز',
    description: 'Golden, crispy potato balls filled with melted mozzarella and seasoned with premium Chinese herbs.',
    descriptionAr: 'كرات بطاطس ذهبية مقرمشة محشوة بجبنة الموزاريلا الذائبة ومتبلة بالأعشاب الصينية الفاخرة.',
    price: 14,
    category: 'sides',
    image: '/images/f3.png',
    tags: ['featured', 'snack'],
    available: true,
    featured: true,
    bestseller: true,
    calories: 280,
  },
  {
    id: '4',
    name: 'Soft Drinks',
    nameAr: 'مشروبات غازية',
    description: 'Perfectly chilled soft drinks, a refreshing match for our signature dishes.',
    descriptionAr: 'انتعاش مثالي مع مجموعة مختارة من المشروبات الغازية الباردة لترافق أطباقنا المميزة.',
    price: 2,
    category: 'drinks',
    image: '/images/f4.png',
    tags: [],
    available: true,
    featured: false,
    bestseller: false,
    calories: 140,
  },
  {
    id: '5',
    name: 'Mineral Water',
    nameAr: 'مياه معدنية',
    description: 'Pure, refreshing mineral water, served with care to complete your experience.',
    descriptionAr: 'مياه نقية ومنعشة تقدم بعناية لتكمل تجربتك بكل بساطة وأناقة.',
    price: 1,
    category: 'drinks',
    image: '/images/f5.png',
    tags: [],
    available: true,
    featured: false,
    bestseller: false,
    calories: 0,
  },
  {
    id: '6',
    name: 'Charcoal Tea',
    nameAr: 'شاهي جمر',
    description: 'An authentic Arabian ritual — premium tea brewed over charcoal embers for a rich aroma and warm, indulgent taste.',
    descriptionAr: 'تجربة عربية أصيلة، شاي فاخر محضر على الجمر برائحة عطرة ومذاق غني يمنحك لحظات من الدفء والاستمتاع.',
    price: 3,
    category: 'drinks',
    image: '/images/f6.png',
    tags: [],
    available: true,
    featured: false,
    bestseller: false,
    calories: 0,
  },
]

export const reviews: Review[] = [
  {
    id: '1',
    customerName: 'محمد العمري',
    rating: 5,
    comment: 'تجربة رائعة! الباستا لذيذة جداً والخدمة سريعة. أفضل مطعم باستا في جدة بدون شك.',
    date: new Date('2024-12-10'),
    verified: true,
    featured: true,
    approved: true,
  },
  {
    id: '2',
    customerName: 'Sarah Al-Rashid',
    rating: 5,
    comment: 'Amazing pasta! The Pastata Ram is absolutely divine. Love the premium feel of the place.',
    date: new Date('2024-12-08'),
    verified: true,
    featured: true,
    approved: true,
  },
  {
    id: '3',
    customerName: 'نورة الزهراني',
    rating: 5,
    comment: 'الباستا بولز رهيبة! القرمشة مثالية والجبن يذوب في الفم. سأعود بالتأكيد.',
    date: new Date('2024-12-05'),
    verified: true,
    featured: true,
    approved: true,
  },
  {
    id: '4',
    customerName: 'Ahmed Hassan',
    rating: 4,
    comment: 'Great taste and presentation. The Ramcine pasta is creamy and rich. Highly recommend!',
    date: new Date('2024-12-01'),
    verified: true,
    featured: false,
    approved: true,
  },
  {
    id: '5',
    customerName: 'فيصل القحطاني',
    rating: 5,
    comment: 'مكان ممتاز وطعام استثنائي. التصميم عصري جداً والجودة تستحق كل ريال.',
    date: new Date('2024-11-28'),
    verified: true,
    featured: true,
    approved: true,
  },
  {
    id: '6',
    customerName: 'Lina Khalid',
    rating: 5,
    comment: 'Absolutely loved the experience! The pasta is fresh, the flavors are incredible, and the ambiance is so Instagram-worthy!',
    date: new Date('2024-11-25'),
    verified: true,
    featured: false,
    approved: true,
  },
]

export const offers: Offer[] = [
  {
    id: '1',
    title: 'Duo Combo',
    titleAr: 'عرض الثنائي',
    description: '2 Pasta dishes + 2 drinks at a special price',
    descriptionAr: '٢ وجبة باستا + ٢ مشروب بسعر مميز',
    discount: 15,
    discountType: 'percentage',
    code: 'DUO15',
    image: '/images/f1.png',
    validUntil: new Date('2025-02-28'),
    active: true,
    featured: true,
  },
  {
    id: '2',
    title: 'Family Feast',
    titleAr: 'وجبة العائلة',
    description: '4 Pasta dishes + 4 drinks + Pastata Balls',
    descriptionAr: '٤ وجبات باستا + ٤ مشروبات + باستاتا بولز',
    discount: 20,
    discountType: 'percentage',
    code: 'FAMILY20',
    image: '/images/f2.png',
    validUntil: new Date('2025-01-31'),
    active: true,
    featured: true,
  },
  {
    id: '3',
    title: 'Happy Hour',
    titleAr: 'ساعة السعادة',
    description: 'Get 10 SAR off any order between 3-5 PM',
    descriptionAr: 'احصل على خصم ١٠ ريال على أي طلب من ٣-٥ عصراً',
    discount: 10,
    discountType: 'fixed',
    code: 'HAPPY10',
    image: '/images/f3.png',
    validUntil: new Date('2025-03-31'),
    active: true,
    featured: false,
  },
]

export const galleryImages: GalleryImage[] = [
  { id: '1', url: '/images/f1.png', alt: 'Pastata Ram', altAr: 'باستاتا رام', category: 'food', featured: true },
  { id: '2', url: '/images/f2.png', alt: 'Ramcine Pasta', altAr: 'رامسين باستا', category: 'food', featured: true },
  { id: '3', url: '/images/f3.png', alt: 'Pastata Balls', altAr: 'باستاتا بولز', category: 'food', featured: true },
  { id: '4', url: '/images/f1.png', alt: 'Pastata Ram close-up', altAr: 'باستاتا رام عن قرب', category: 'food', featured: false },
  { id: '5', url: '/images/f3.png', alt: 'Pastata Balls', altAr: 'باستاتا بولز', category: 'food', featured: false },
  { id: '6', url: '/images/f2.png', alt: 'Ramcine', altAr: 'رامسين', category: 'food', featured: false },
  { id: '7', url: '/images/f4.png', alt: 'Soft Drinks', altAr: 'مشروبات غازية', category: 'drinks', featured: false },
  { id: '8', url: '/images/f5.png', alt: 'Water', altAr: 'مياه', category: 'drinks', featured: false },
  { id: '9', url: '/images/f6.png', alt: 'Tea', altAr: 'شاي', category: 'drinks', featured: false },
]

// Working hours — daily 3:00 PM to 3:00 AM
export const workingHours = {
  ar: 'يومياً · ٣:٠٠ مساءً – ٣:٠٠ فجراً',
  en: 'Daily · 3:00 PM – 3:00 AM',
}

export const businessHours: BusinessHours[] = [
  { day: 'Sunday', dayAr: 'الأحد', open: '3:00 PM', close: '3:00 AM', closed: false },
  { day: 'Monday', dayAr: 'الاثنين', open: '3:00 PM', close: '3:00 AM', closed: false },
  { day: 'Tuesday', dayAr: 'الثلاثاء', open: '3:00 PM', close: '3:00 AM', closed: false },
  { day: 'Wednesday', dayAr: 'الأربعاء', open: '3:00 PM', close: '3:00 AM', closed: false },
  { day: 'Thursday', dayAr: 'الخميس', open: '3:00 PM', close: '3:00 AM', closed: false },
  { day: 'Friday', dayAr: 'الجمعة', open: '3:00 PM', close: '3:00 AM', closed: false },
  { day: 'Saturday', dayAr: 'السبت', open: '3:00 PM', close: '3:00 AM', closed: false },
]

// PASTATARAM branches
export interface Branch {
  id: number
  nameAr: string
  nameEn: string
  detailAr: string
  detailEn: string
}

export const branches: Branch[] = [
  {
    id: 1,
    nameAr: 'جدة - القرنية',
    nameEn: 'Jeddah - Al Qurainiyah',
    detailAr: 'بجوار الهيئة الاقتصادية',
    detailEn: 'Next to the Economic Authority',
  },
  {
    id: 2,
    nameAr: 'حي السنابل',
    nameEn: 'Al Sanabel District',
    detailAr: 'خلف ماكدونالدز',
    detailEn: 'Behind McDonald’s',
  },
  {
    id: 3,
    nameAr: 'حي الواحة',
    nameEn: 'Al Waha District',
    detailAr: 'بجوار المساحة الجيولوجية · مقابل الممشى',
    detailEn: 'Next to the Geological Survey · Opposite the walkway',
  },
]

export const cmsContent: CMSContent = {
  heroTitle: 'A Modern Pasta Experience Combining Elegance & Exceptional Taste',
  heroTitleAr: 'تجربة باستا عصرية تجمع بين الأناقة والطعم الاستثنائي',
  heroSubtitle: 'Italian flavors carefully crafted to give you an unforgettable experience',
  heroSubtitleAr: 'نكهات إيطالية مصممة بعناية لتمنحكم تجربة لا تُنسى',
  heroImage: '/images/f1.png',
  aboutText: 'PASTATARAM is a premium fast-casual pasta brand born in Jeddah. We believe great pasta should be accessible, fast, and absolutely delicious. Every dish is crafted with premium Italian-inspired ingredients.',
  aboutTextAr: 'باستاتا رام هي علامة تجارية للباستا الفاخرة غير الرسمية ولدت في جدة. نؤمن بأن الباستا الرائعة يجب أن تكون في متناول الجميع، سريعة، ولذيذة تماماً. كل طبق يُصنع بمكونات فاخرة مستوحاة من الطراز الإيطالي.',
  businessHours,
  socialLinks: {
    instagram: 'https://instagram.com/pastataram',
    tiktok: 'https://tiktok.com/@pastataram',
    snapchat: 'https://snapchat.com/add/pastataram',
    whatsapp: 'https://wa.me/966501938696',
  },
  whatsappNumber: '966501938696',
  phone: '050 193 8696',
  address: 'Jeddah - Al Qurainiyah - Next to the Economic Authority',
  addressAr: 'جدة - القرنية - بجوار الهيئة الاقتصادية',
}
